### PR TITLE
Make tag value be an Option<T>

### LINKED ISSUE #5: Tag value should be Option<T>
Currently you represent the value of a tag as string. This does not work well for value-less options. An idea would be to replace that `T` with `Option<T>` and set it to `Some(value)` for keys with value and to `None` for those without.

Your example output from the readme would then look like this:

``` rust
Ok(
  IrcMessage {
    tags: {
      best: Some(super),
      single: None
    },
    prefix: Some(test!me@test.ing),
    command: Some(FOO),
    params: [bar, baz, quux, This is a test]
  }
)
```

I would not mind implementing this myself and submitting a pull request. However i want to put this up for discussion first.

I am very well aware that this would be a breaking change, however it is almost unevitable, in case you want to ever properly support tags which have the actual value `true`. Apart from that it fits better in rusts type system

### PR DESCRIPTION
**Pull request by Kilobyte22**
Fixes #5

### CODE REVIEW

**Comment by TyOverby** [comment]
looks good!  Thanks for the contribution!

**Comment by Kilobyte22** [comment]
Don't forget to publish the crate ;)

**Comment by TyOverby** [comment]
Oh, actually, could you also make a change to the readme to update the example?

**Comment by TyOverby** [comment]
I decided to update the version to 1.0.  It's published now.

**Pull request merged**
